name: DL4CV24-second-assignment

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - name: Synchronizing repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: success() || failure()
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu
      - name: Test network implementation
        if: success() || failure()
        run: |
          pytest tests/test_network.py
      - name: Test training implementation
        if: success() || failure()
        run: |
          pytest tests/test_train_one_epoch.py
      - name: Test evaluation implementation
        if: success() || failure()
        run: |
          pytest tests/test_evaluate_one_epoch.py
      - name: Test train+eval implementation
        if: success() || failure()
        run: |
          pytest tests/test_train_and_evaluate_model.py
      - name: Test early stopping implementation
        if: success() || failure()
        run: |
          pytest tests/test_early_stopping.py
      - name: Test scheduler implementation
        if: success() || failure()
        run: |
          pytest tests/test_scheduler.py
      - name: Test save weight implementation
        if: success() || failure()
        run: |
          pytest tests/test_save_weights.py
      - name: Test load weights implementation
        if: success() || failure()
        run: |
          pytest tests/test_load_weights.py
      - name: Test frozen weights implementation
        if: success() || failure()
        run: |
          pytest tests/test_frozen_weights.py
      - name: Test stratified lr implementation
        if: success() || failure()
        run: |
          pytest tests/test_stratified_lr.py
      - name: Test augmentation implementation
        if: success() || failure()
        run: |
          pytest tests/test_augmentations.py